version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Run Test Coverage
          command: ./gradlew clean build jacocoTestReport
      - run:
          name: Upload to CodeCov
          command: bash <(curl -s https://codecov.io/bash)